# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557a9abc8edf065c3e7c6a5f4dbfc3b15bc0d7bc2ff658e4ae9c7428cbec10d45a4dc6cc73df2d13c76993c2e4e5d9e1f76c155befc3b1f9a8eb61f4b72e0071
  sender_email: skanatestsender
  sender_password: test1pass
test:
  secret_key_base: e9480dd68a190ea9c3ba2c263e1b041e9fcc426f1f4cd62a58db51c0ffdec889318a51128a9c8a7cf47711afa117ed49e81260f0fdd67b38ee8167509e88628b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
